include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_type_to_string
    - avoid_void_async
    - await_only_futures
    - discarded_futures
    - lines_longer_than_80_chars
    - no_literal_bool_comparisons
    - noop_primitive_operations
    - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_if_null_operators
    - prefer_int_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_void_to_null
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - switch_on_type
    - unawaited_futures
    - unnecessary_async
    - unnecessary_breaks
    - unnecessary_ignore
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_unawaited
    - unsafe_variance
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_null_aware_elements
    - use_super_parameters
    - valid_regexps
    - void_checks

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
