name: dgt
description: A Dart command-line app to help with Gerrit issues
version: 1.0.0

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.3
  args: ^2.7.0
  collection: ^1.19.1
  http: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
